import React, { useState } from 'react'
import Head from 'next/head'
import { useRouter } from "next/router";

import Layout from "../../components/common/Layout";
import PageHead from '../../components/common/PageHead'
import Fab from '../../components/common/Fab'
import NewEventModal from '../../components/event/NewEventModal'
import EventListItem from "../../components/event/EventListItem";

import events from '../../styles/my_events.module.scss'
import s from '../../styles/schedule.module.scss'
import U from "../../utile";

export const getServerSideProps = async (ctx) => {
    return U.verifyAuthState({ ctx });
};

const MyEventsScreen = props => {
    const { isSignOut = false } = props;
    const router = useRouter()
    const [isActive, setIsActive] = React.useState(false)
    const { uniqueId } = router.query;

    const _handleModal = () => {
        if (isActive) {
            setIsActive(false)
        } else {
            setIsActive(true)
        }
    }

    return (
        <Layout isSignOut={isSignOut}>
            <Head>
                <title>Open</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={events.my_event}>
                <PageHead title={"登録したイベント"} />
                <div className={events.my_event_row}>
                    <div className={events.my_event_row_head}>
                        <h3 className={events.my_event_row_head_text}>
                            2022年6月
                        </h3>
                    </div>
                    <ul className={s.schedule_list}>
                        <EventListItem />
                        <EventListItem />
                        <EventListItem />
                        <EventListItem />
                    </ul>
                </div>
            </div>
            <Fab onClick={_handleModal} />
            <NewEventModal onCloseModal={_handleModal} isActive={isActive} />
        </Layout>
    )
}

export default MyEventsScreen