import React, { useState } from 'react'
import Head from 'next/head'
import nookies from "nookies";

import { useRouter } from "next/router";
import Layout from "../../components/common/Layout";
import AutherProfile from '../../components/calendar/AutherProfile'
import CustomFullCalendar from '../../components/calendar/CustomFullCalendar'
import Fab from '../../components/common/Fab'
import NewEventModal from '../../components/event/NewEventModal'
import ScheduleDetailModal from '../../components/schedule/ScheduleDetailModal'
import U from "../../utile";

export const getServerSideProps = async (ctx) => {
    return U.verifyAuthState({ ctx });
};

const CalendarScreen = props => {
    const { isSignOut = false } = props;

    const router = useRouter()
    const [isActiveEventModal, setIsActiveEventModal] = React.useState(false)
    const [isActiveScheduleDetailModal, setIsActiveScheduleDetailModal] = React.useState(false)
    const { uniqueId } = router.query;

    const _handleEventModal = () => {
        if (isActiveEventModal) {
            setIsActiveEventModal(false)
        } else {
            setIsActiveEventModal(true)
        }
    }

    const _handleScheduleModal = () => {
        if (isActiveScheduleDetailModal) {
            setIsActiveScheduleDetailModal(false)
        } else {
            setIsActiveScheduleDetailModal(true)
        }
    }

    return (
        <Layout page={"/calendar"} isSignOut={isSignOut}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AutherProfile />
            <CustomFullCalendar onClickDay={_handleScheduleModal} />
            <Fab onClick={_handleEventModal} />
            <NewEventModal isActive={isActiveEventModal} onCloseModal={_handleEventModal} />
            <ScheduleDetailModal isActive={isActiveScheduleDetailModal} onCloseModal={_handleScheduleModal} />
        </Layout>
    )
}

export default CalendarScreen