import Head from 'next/head'
import { useRouter } from "next/router";
import Layout from "../../components/common/Layout";
import CustomFullCalendar from '../../components/calendar/CustomFullCalendar'
import U from "../../utile";

export const getServerSideProps = async (ctx) => {
    U.verifySessionCookie();

    return {
        props: {
            email: "",
        },
    };
};


const CalendarScreen = () => {
    const router = useRouter()
    const { groupId } = router.query;

    return (
        <Layout>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CustomFullCalendar />
        </Layout>
    )
}

export default CalendarScreen