import React, { useState } from 'react'
import Head from 'next/head'
import { useRouter } from "next/router";
import Layout from "../../components/common/Layout"
import InputRow from '../../components/form/InputRow'
import TextareaRow from '../../components/form/TextareaRow'
import NewProfileForm from '../../components/form/NewProfileForm'

import PageHead from '../../components/common/PageHead'
import profileStyle from '../../styles/profile.module.scss'
import form from '../../styles/form.module.scss'
import API from "../../api";
import U from "../../utile";

export const getServerSideProps = async (ctx) => {
    return U.verifyAuthState({ ctx });
};

const ProfileScreen = props => {
    const router = useRouter()
    const { isSignOut = false, profile = {}, group = {} } = props;

    return (
        <Layout isSignOut={isSignOut}>
            <Head>
                <title>Open</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={profileStyle.profile}>
                <PageHead title={"プロフィール"} />
                <NewProfileForm profile={profile} group={group} />
            </div>
        </Layout >
    )
}

export default ProfileScreen