import React from 'react'
import { useRouter } from "next/router";
import Head from 'next/head'

import Layout from "../components/common/Layout";
import common from "../styles/common.module.scss";
import header from "../styles/header.module.scss";
import lp from "../styles/landing_page.module.scss";
import U from "../utile";

const TopScreen = () => {
  const router = useRouter()

  const userId = "";

  const _navSignUp = () => {
    router.push('/signup')
  }
  const _navSignIn = () => {
    router.push('/signin')
  }
  const _navCalendar = () => {
    const groupId = "test";
    router.push(`/calendars/${groupId}`)
  }
  const _navProfile = () => {
    router.push(`/profile/${userId}`)
  }
  const _navSetting = () => {
    router.push(`/setting/${userId}`)
  }

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={lp.design}>
        <p>
          <a onClick={_navSignUp} className={header.header_nav_list_item_text}>
            新規登録
          </a>
        </p>
        <p>
          <a onClick={_navSignIn} className={header.header_nav_list_item_text}>
            ログイン
          </a>
        </p>
        <p>
          <a onClick={_navCalendar} className={header.header_nav_list_item_text}>
            カレンダー
          </a>
        </p>
        <p>
          <a onClick={_navProfile} className={header.header_nav_list_item_text}>
            プロフィール
          </a>
        </p>
        <p>
          <a onClick={_navSetting} className={header.header_nav_list_item_text}>
            設定
          </a>
        </p>
      </div>
    </Layout>
  )
}

// export const getServerSideProps = async (ctx) => {
//   // const cookies = nookies.get(ctx);
//   // const session = cookies.session || "";
//   // const user = await U.getFirebaseAdminUser({ session })

//   // if (!user) {
//   //   return {
//   //     redirect: {
//   //       destination: "/login",
//   //       permanent: false,
//   //     },
//   //   };
//   // }

//   // return {
//   //   props: {
//   //     email: user.email,
//   //   },
//   // };
// };


export default TopScreen;