import Head from 'next/head'
import Layout from "../components/common/Layout";
import CustomFullCalendar from '../components/calendar/CustomFullCalendar'

const SignInScreen = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomFullCalendar />
    </Layout>
  )
}

// export const getServerSideProps = async (ctx) => {
//     return null
// };

export default SignInScreen;